[tool.poetry]
name = "generative-models"
version = "0.1.0"
description = ""
authors = ["Wian Stipp"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
torch = "^2.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
